spring.application.name=springboot-restful-services
spring.datasource.url=jdbc:mysql://localhost:3600/user_management
spring.datasource.username=root
spring.datasource.password=kaitare


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
server.port=8081