spring.application.name=springDataJPA

spring.datasource.url=jdbc:mysql://localhost:3600/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=kaitare

server.port=8082
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#none,create-only, drop, create-drop , validate, update.
spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.show-sql=true
