spring.application.name=sendEmail

# SMTP configuration for sending emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ex.1@gmail.com
# App Password (spaces removed)
spring.mail.password=mntublvpdilbygll
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

server.port = 8082
# Email recipient (for demo purposes)
app.mail.recipient=landryas@gmail.com
