spring.application.name=ereactive
spring.r2dbc.url=r2dbc:postgres://localhost:5432/ereactive
spring.r2dbc.username=postgres
spring.r2dbc.password=kaitare
spring.sql.init.platform=postgres
spring.sql.init.mode=always
server.port=8080
spring.sql.init.schema-locations=classpath:schema.sql